model:
  encoder:
    type: UNet
    gnorm_affine: True 
  decoder:
    type: UNet
  latent_channel: 32
  spatial_softmax:
    kernel_size: 21
    strength: 5
  num_cluster: 32
  top_k: 4
  gau_var: 0.05
  alpha_blending: False
data:
  dataset:
    name: CelebA
    dir: /ubc/cs/research/kmyi/datasets
    sub_name: CelebA
  preprocess:
    image_size: 80
    color_jitter: False
training:
  epochs: 1000
  batch_size: 32
  lr:
    feature: 0.001
    prototype: 0.1
    num_opt_sw: 8
  checkpoint:
    save_weights: True
    resume: False
  set_seed: False
  scheduler:
    summary_interval: 0.5
    save_interval: 5
    valid_interval: 5
    stop_time: -1
  loss:
    fixed_prototype: False
    feature:
      recon:
        type: Perceptual
        weight: 1
        pretrained_path: ./pretrained/vgg16
      cluster:
        weight: 0.01
      eqvar:
        activate: True
        h_weight: 0.01
        f_weight: 100
    prototype:
      sw:
        weight: 1
viz:
  log_dir: ./logs
  show_all_debug: False
  plot_gt_tsne: False

metadata:
  name: 'celeba'
  comments: ''
  model_dir: './saved_models'
  result_root_folder: './results'


